# TODO: This is just a temporary solution.
import os

from dotenv import load_dotenv

load_dotenv()

# Server
BOT_URL = os.getenv("BOT_URL")
HOST = os.getenv("HOST")
PORT = os.getenv("PORT")

# Bot
BOT_TOKEN = os.getenv("BOT_TOKEN")
ADMIN_ID = int(os.getenv("ADMIN_ID"))
MAIN_BOT_PATH = os.getenv("MAIN_BOT_PATH")
OTHER_BOTS_PATH = os.getenv("OTHER_BOTS_PATH")

# Debug
DEBUG = True if int(os.getenv("DEBUG")) == 1 else False

# Cryptobot
CRYPTO_TOKEN = os.getenv("CRYPTO_TOKEN")
CRYPTO_TOKEN_TEST = os.getenv("CRYPTO_TOKEN_TEST")

# Ton wallet
WPAY_STORE_API_KEY = os.getenv("WPAY_STORE_API_KEY")

# Tegro money
TEGRO_API_URL = os.getenv("TEGRO_API_URL")
TEGRO_SHOP_ID = os.getenv("TEGRO_SHOP_ID")
TEGRO_API_KEY = os.getenv("TEGRO_API_KEY")
TEGRO_SECRET_KEY = os.getenv("TEGRO_SECRET_KEY")

# Unitpay
UNIT_API_URL = os.getenv("UNIT_API_URL")
UNITPAY_PROJECT_ID = os.getenv("UNITPAY_PROJECT_ID")
UNITPAY_SECRET_KEY = os.getenv("UNITPAY_SECRET_KEY")

# Cloudpayments
CLOUDPAYMENTS_API_URL = os.getenv("CLOUDPAYMENTS_API_URL")
CLOUDPAYMENTS_PUBLIC_ID = os.getenv("CLOUDPAYMENTS_PUBLIC_ID")
CLOUDPAYMENTS_SECRET_KEY = os.getenv("CLOUDPAYMENTS_SECRET_KEY")

# SmmPanel
SMMPANEL_KEY = os.getenv("SMMPANEL_KEY")
CHARGE_PER_COUNT = 1000
BASE_USD_RUB_RATE = 95

# SmoService
SMOSERVICE_KEY = os.getenv("SMOSERVICE_KEY")
SMOSERVICE_USER_ID = os.getenv("SMOSERVICE_USER_ID")

# Replenishment
REPLENISH_AMOUNT_VARIANTS = [250, 500, 1000, 5000, 10000, 25000]
MIN_REPLENISH_AMOUNT = 1

CHEQUE_MIN_SUM = 0.1
CHEQUE_MIN_QUANTITY = 1
CHEQUE_CREDIT_PER_SUBSCRIBE = 0.5
CHEQUE_DEFAULT_SUBSCRIBES = 3
CHEQUE_MAX_SUBSCRIBES = 5
BALANCE_PRECISION = 4
PRODUCT_PRICE_PRECISION = 4

PAGINATION_CATEGORIES_PER_PAGE = 95

# Referrals
NEW_REFERRAL_BONUS = 5
REFERRAL_REPLENISH_BONUS_PERCENTS = [12, 4]

CHECK_ORDER_STATUS_INTERVAL = int(os.getenv("CHECK_ORDER_STATUS_INTERVAL"))
AUTO_STARTING_ORDERS_INTERVAL = int(os.getenv("AUTO_STARTING_ORDERS_INTERVAL"))

FAQ_URL = os.getenv("FAQ_URL")
HELP_URL = os.getenv("HELP_URL")

BROADCAST_MESSAGES_PER_SECOND = float(
    os.getenv("BROADCAST_MESSAGES_PER_SECOND")
)
